### ISSUE TITLE
能不能出一个基于MIT协议的阉割版？

### ISSUE THREAD

**Issue by LiuPeiqiCN** [programClown/QFluentWidgets#1]
原项目[PyQt-Fluent-Widgets](https://github.com/zhiyiYo/PyQt-Fluent-Widgets)已经由MIT协议改为GPL协议，商业付费后可以基于LGPL协议，这些协议都不宽松。但是如果改用之前MIT协议的旧版本可以规避该问题，就算版本比较旧，部分功能被阉割也没事。

**Comment by programClown** [comment]
尊重原作，谢谢！

**Comment by LiuPeiqiCN** [comment]
是的是的，有道理，尊重原作，没必要钻这种空子。原项目商业付费对于我还是有点贵，目前只好基于其他项目造轮子了。
