### ISSUE TITLE
FluShortInfoBar 点击多次异常

### ISSUE THREAD

**Issue by 860000023** [programClown/QFluentWidgets#6]
FluShortInfoBar 的示例多次点击会异常,中断在
void FluShortInfoBar::disappear() 的
 m_opacityAni->setStartValue(1);

**Comment by 860000023** [comment]
准备的来说是当信息窗口出现的时候 ,如果我点击信息窗口界面的关闭按钮,就会造成这个问题.应该是我释放了这个窗口.但是TIMER事件没有判断还是会释放这个窗口

**Comment by 860000023** [comment]
在  disappear函数中QPointer<LYShortInfoBar> ptr(this);
QTimer::singleShot(m_nDisappearDuration, [=]() {
	if (!ptr)
		return;  // 如果对象已经被删除，就返回    这样就没有问题了.不知道我的解决方案对不对,我是QT新手.

**Comment by 860000023** [comment]
搞错地方了...

**Comment by mowangshuying** [comment]
啊？
