### ISSUE TITLE
请问此QFluentWidgets是彼[QFluentWidgets](https://qfluentwidgets.com/pages/about/)吗？

### ISSUE THREAD

**Issue by liaodalin19903** [programClown/QFluentWidgets#8]
请问，

1. 您做的项目是此[QFluentWidgets](https://qfluentwidgets.com/pages/about/)吗？
2. 请问是否支撑PySide呢？
3. 可以加载到Qt Designer中使用吗？

**Comment by programClown** [comment]
不是
